services:
  - type: web
    name: trupti
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn food_management.wsgi:application
    postDeployCommand: ./post_deploy.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: food_management.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: ALLOWED_HOSTS
        value: "trupti.onrender.com"
    plan: free
    region: singapore
